### ISSUE TITLE
Suggestion: adjust peerDependencies to match ng 12 and above

### ISSUE THREAD

**Issue by meszabalu-mv** [willmendesneto/ngx-skeleton-loader#110]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Current behavior**
After installing the package under a project with eg. `"@angular/core": "~11.0.6"` installed you'll get an error in compile time with the following message:
```
Error: node_modules/ngx-skeleton-loader/lib/ngx-skeleton-loader.component.d.ts:20:21 - error TS2694: Namespace '"/Users/meszarosbalazs/Projects/Motivosity/Motivosity/src/main/webapp/new-webapp/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

20     static ɵfac: i0.ɵɵFactoryDeclaration<NgxSkeletonLoaderComponent, [{ optional: true; }]>;
```
During npm install I got no warning/error regarding wrong peer dependencies.

**Expected behavior**
During npm install user should be warned about not using Angular 12+.

**Reproduction of the problem**
Described above ^^

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Browser:** does not apply

  

- **Language:**  Typescript/ES6

- **Node (if applicable):** `node --version` = `v14.17.6`

**Comment by FactorMouk** [comment]
Same problem here.

**Comment by willmendesneto** [comment]
Hi folks 👋 

Firstly, thanks for raising this issue. Sharing some details about the issue:

- Since `@angular/cli` changed it's way to distribute the bundle files, this module had to follow it's rules to keep up-to-date with the current versions and moving forward with Angular definitions;
- Since this is related to internal tooling, it might be quite hard to have some validation on that and maintain such automation to get it checked properly (not just package versions check);

I tried my best to get some automation for it, but the effort wasn't worth it. What will be done instead is to update the peerDependencies fields on the module to get up-to-date with this breaking change, and let `@angular/cli` handling with that.

Once again, thanks for raising this issue. Unfortunately, this won't be possible easily and leave this responsibility to Angular CLI looks a sensible thing to do in that case.

Closing this issue for now, thanks folks!
