### ISSUE TITLE
Can't bind to 'theme' since it isn't a known property of 'ngx-skeleton-loader'

### ISSUE THREAD

**Issue by simoneraffaelli** [willmendesneto/ngx-skeleton-loader#168]
When I try to use the theme property the project won't compile and run and pops out the error written in the title.
![image](https://github.com/willmendesneto/ngx-skeleton-loader/assets/6719190/657c95f5-c271-424a-910c-6179312aa653)

I tried with the module imported in the component mosule and also in the app module but the error persist. Any ideas?

Angular Version: 15.1.2
ngx-skeleton-loader Version: 8.0.0

- [ x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request

**Comment by willmendesneto** [comment]
Hi @simoneraffaelli , thanks for raising this issue.

Could you simulate the issue in Stackblitz and share the link here, please? E.G: https://stackblitz.com/edit/ngx-skeleton-loader-user-card-component-sample?file=src%2Fapp%2Fapp.component.ts

This usually happens due to app misconfiguration. It can be because the app isn't importing the NgxSkeletonLoader module, for example. So I might need more information if that's not the issue.

You can find more info about that on the [Angular Docs - List of Dev Errors Page](https://angular.dev/errors/NG8002)

**Comment by willmendesneto** [comment]
Closing this issue due to lack of feedback. Thanks @simoneraffaelli
