### ISSUE TITLE
Custom-content appearance skeleton sometimes does not appear

### ISSUE THREAD

**Issue by lmarquinez** [willmendesneto/ngx-skeleton-loader#173]
**I'm submitting a ...** (check one with "x")

- [X ] bug report => search github for a similar issue or PR before submitting
- [ ] feature request

**Current behavior**

I am using svg images to display as custom-content appearance. The problem is that the skeleton sometimes does not appear. If I go to the network section of the browser, I can see that the request is made and this sometimes takes time or remains pending so the image, the skeleton in this case, is not displayed.

**Expected behavior**

To always appear.

**Reproduction of the problem**

```
<div class="item" *ngIf="(isLoaderVisible$ | async)" >
  <ngx-skeleton-loader appearance="custom-content">
    <div class="skltn-loader">
        <img src="assets/images/loader.svg">
    </div>
  </ngx-skeleton-loader>
</div>
```

**Please tell us about your environment:**

Angular v16

- **Browser:** all 

- **Language:**  TypeScript ^4.9.5 ES2022

- **Node:** `node --version` = v18.20.4

**Comment by elbanyaoui** [comment]
Thank you for your bug report. To address this issue, it might be better to replace the image reference with the direct SVG code. By embedding the SVG code directly into your HTML, you can avoid potential delays or issues related to network requests for the image file.

**Comment by willmendesneto** [comment]
As mentioned by @elbanyaoui , the issue in this case is related to your approach when using SVG directly. There are some techniques you might use to make sure the content will be loaded or event adding this svg as inline content into your HTML file. This would avoid such issue to be happening.

Closing this issue since it's not related to the module itself. Thanks @lmarquinez
