### ISSUE TITLE
Error Type 'string' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by supervardon** [willmendesneto/ngx-skeleton-loader#59]
I've previous used the loader in Angular 9 successfully, however when using it in Angular 11, I'm just getting the error Type 'string' is not assignable to type 'number'.

I've followed the instructions and installed the package, imported the module and then added the html.  But I'm getting this error on the html itself.  Can I confirm that this is an issue, and if there is a work around for it?

`<ngx-skeleton-loader count="5" appearance="circle"></ngx-skeleton-loader>`

```
import { NgxSkeletonLoaderModule } from 'ngx-skeleton-loader';

  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    NgxSkeletonLoaderModule
  ],

```

**Comment by willmendesneto** [comment]
Hi @supervardon , thanks for raising this issue!

I just published a new version of the package with the fix. Please, update your project to use `ngx-skeleton-loader@2.8.0`. You can find more details about it in this commit https://github.com/willmendesneto/ngx-skeleton-loader/commit/84ea4418c8815d3a3d744f8929de9d2a3bc8c0be

Closing this issue since it's solved. Thanks again!
