### ISSUE TITLE
ngAcceptInputType_animation is too permissive

### ISSUE THREAD

**Issue by rafaelss95** [willmendesneto/ngx-skeleton-loader#61]
**I'm submitting a ...** (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request

**Current behavior**
Since 2.8.0 we can pass to `animation` something like `true` or **any** `string` and the template won't fail (even under strict mode). It happens because actually `ngAcceptInputType_animation` masks the real type, as it is too permissive:

https://github.com/willmendesneto/ngx-skeleton-loader/blob/2bd255c331bed7eb026a91d0385cc6930ff806ec/projects/ngx-skeleton-loader/src/lib/ngx-skeleton-loader.component.ts#L24

The allowed types are:

https://github.com/willmendesneto/ngx-skeleton-loader/blob/2bd255c331bed7eb026a91d0385cc6930ff806ec/projects/ngx-skeleton-loader/src/lib/ngx-skeleton-loader.component.ts#L35-L36

<hr>

**Expected behavior**
Unless I'm missing something the `ngAcceptInputType_animation` doesn't seem to help in anything there and thus can be safely removed.

**Reproduction of the problem**
https://stackblitz.com/edit/angular-ivy-b34arq

**Please tell us about your environment:**

- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX |
  Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

  

- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular 11, ngx-skeleton-loader 2.9.0.

**Comment by willmendesneto** [comment]
The dev mode message was added to describe that behaviour. Also, Angular Universal complains about don't have a boolean expressely added, so its required.

The type was updated to 
<img width="454" alt="Screen Shot 2021-02-21 at 10 19 21 pm" src="https://user-images.githubusercontent.com/1252570/108645860-ecb0f780-7492-11eb-89aa-22019abd1abd.png">


Since it's not a problem and it's covered, I'm closing this issue. Thanks again for raising that!

**Comment by rafaelss95** [comment]
> Also, Angular Universal complains about don't have a boolean expressely added, so its required.

Aha, I didn't know that part, thanks for the info.
