### ISSUE TITLE
Parent Container dependent Styling

### ISSUE THREAD

**Issue by FabianDever** [willmendesneto/ngx-skeleton-loader#89]
Hey,

I'm trying to style the skeletion-loader realtive to its parent like so:

```    
<ngx-skeleton-loader  count="1" appearance="" [theme]="{ height: '90%' }"></ngx-skeleton-loader>
```

Am I doing anything wrong, or is it just not possible?

Also flexbox support would be geat.

Fabian

**Comment by willmendesneto** [comment]
Hi @FabianDever 

Could you elaborate more your issue, please? Not sure if I'm following. Also, it would be great if you can create an example on Stackblitz, so that can be solved faster
https://stackblitz.com/edit/ngx-skeleton-loader-user-card-component-sample

**Comment by willmendesneto** [comment]
Hey @FabianDever 

I just got able to simulate your issue. Actually, it's something on the app side, not on the package itself. The parent should have some minimal css for display and such, when the component should have or width with the value in pixels and height as using the value as you wish (px, %, etc).

I'm sharing here a link of the sample I've done applying your scenario +. the correct configuration. Also, feel free to have a look at the Demo links on the README.md of this project to get more information about configuration, usage, etc. (https://github.com/willmendesneto/ngx-skeleton-loader#demo)

Closing this issue for now since it's not related to the package itself. Thanks @FabianDever for raising the issue!

**Comment by FabianDever** [comment]
Hey @willmendesneto,
thanks for your answer, although i don't quite unterstand it. :D
I've created an example stakblitz, and i just can't get the result i wish for.
I'd like all the loaders to be the height and width as their parents.
It would be great if you cloud take a look at it.

https://stackblitz.com/edit/ngx-skeleton-loader-user-card-component-sample-ynqdap?file=app/app.component.html
